spring:
  data:
    redis:
      host: ENC(kufQiJ3iE16ijM5rWwRw+5oB6DHm2H3QWgX+MIio6dsCxR7iL8IAGOyt6+ArdCQPbRYEDQgGEQJS0SZVYPR0fUuFRLDwkIEm)
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(ZiH1qDXi18HI1FVhYeSbF8sGaC/eo4RCub043jYe8SvuTxgNA/0VU0c5VEQv8X74yoDLxhXOvvxXtHbfLG4d4oyrX8f++46pm/3EZqKhQf+7N5oWjy4IQg==)
      username: ENC(hUSFqr+kl28AIVDKBfyRHA==)
      password: ENC(h+KCgHzWodMO7mdSt9Zjn+WIsq5Uuiuv)
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(ZiH1qDXi18HI1FVhYeSbF8sGaC/eo4RCub043jYe8SvuTxgNA/0VU0c5VEQv8X74yoDLxhXOvvxXtHbfLG4d4oyrX8f++46pm/3EZqKhQf+7N5oWjy4IQg==)
      username: ENC(hUSFqr+kl28AIVDKBfyRHA==)
      password: ENC(h+KCgHzWodMO7mdSt9Zjn+WIsq5Uuiuv)
  flyway:
    baseline-version: 1


server:
  tomcat:
    threads:
      max: 100          # maxThreads
      min-spare: 20

log:
  file:
    path: /ody-prod-logs
