spring:
  data:
    redis:
      host: ENC(TynN9wdVE74kyvps7isjEdUV3mK4D+3OFi6DL9XgvjflFfGBG88U3mMVxJuiMZhN+kXMo27GP4R192frm84k921qxgeUyHTk)
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(ZiH1qDXi18HI1FVhYeSbF8sGaC/eo4RCub043jYe8SvuTxgNA/0VU0c5VEQv8X74yoDLxhXOvvxXtHbfLG4d4oyrX8f++46pm/3EZqKhQf+7N5oWjy4IQg==)
      username: ENC(hUSFqr+kl28AIVDKBfyRHA==)
      password: ENC(h+KCgHzWodMO7mdSt9Zjn+WIsq5Uuiuv)
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(ZiH1qDXi18HI1FVhYeSbF8sGaC/eo4RCub043jYe8SvuTxgNA/0VU0c5VEQv8X74yoDLxhXOvvxXtHbfLG4d4oyrX8f++46pm/3EZqKhQf+7N5oWjy4IQg==)
      username: ENC(hUSFqr+kl28AIVDKBfyRHA==)
      password: ENC(h+KCgHzWodMO7mdSt9Zjn+WIsq5Uuiuv)
  flyway:
    baseline-version: 1

log:
  file:
    path: /ody-prod-logs
