name: backend-cd-coli

on:
  push:
    branches:
      - coli

env:
  DOCKERHUB_REPOSITORY: cdtest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Seoul'

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
        with:
          ref: coli

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check system timezone
        run: |
          echo "Current date and time: $(date)"
          echo "TZ environment variable: $TZ"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Clean Build With Gradle Wrapper
        run: ./gradlew clean build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build And Push
        run: docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-coli -f Dockerfile . --push

  pull-and-deploy:
    needs: build-and-push
    runs-on: coli-test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Clean Up Legacy Image
        run: |
          docker compose down || true
          docker rmi $(docker images -q) -f || true

      - name: Docker Compose up
        run: |
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          export DOCKERHUB_REPOSITORY=$DOCKERHUB_REPOSITORY
          export PROD_MYSQL_PASSWORD=${{ secrets.TEST_MYSQL_PASSWORD }}
          export JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_PASSWORD }}
          export TAG=${{ github.sha }}-prod_v2
          docker compose up -d


      - name: Check Docker Process
        if: always()
        run: docker ps
